DB_HOST_SUPABASE = "aws-1-us-east-1.pooler.supabase.com"
DB_PORT_SUPABASE = "5432"
DB_NAME_SUPABASE = "postgres"
DB_USER_SUPABASE = "postgres.utcyllupkvhcccsljutf"
DB_PASSWORD_SUPABASE = "Levent2026.."